info:
  component: Liquid Democracy Api

logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: DEBUG

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost

---
spring:
  profiles: test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: localhost
      database: dbliqdem

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
