info:
  component: Liquid Democracy Api

logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: INFO
    org.springframework.security: DEBUG
    
security:
  user:
    name: sparlant
    password: pwd
  oauth2:
    sso:
      login-path: /login_success
    client:
      clientId: TODO
      clientSecret: TODO
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?hd=zenika.com
      clientAuthenticationScheme: query
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-prod
  data:
    mongodb:
      host: localhost
logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: INFO
    org.springframework.security: ERROR     
  file: ./logs/liquid_democracy_api.log

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem

---      
spring:
  profiles: docker-test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
