info:
  component: Liquid Democracy Api
  
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: /
    redirectUrlFailure: /
    
spring:
  social:
    google:
      appId: 
      appSecret: 

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-prod
  data:
    mongodb:
      host: localhost
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: http://localhost:8081/TestApi/success.html
    redirectUrlFailure: http://localhost:8081/TestApi/failure.html

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: http://localhost:3000
    redirectUrlFailure: http://localhost:3000/#/loginfailed

---      
spring:
  profiles: docker-test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
