info:
  component: Liquid Democracy Api

logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: INFO
    org.springframework.security: DEBUG

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-prod
  data:
    mongodb:
      host: localhost
logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: INFO
    org.springframework.security: DEBUG     
  file: ./logs/liquid_democracy_api.log

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem

---      
spring:
  profiles: docker-test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
