info:
  component: Liquid Democracy Api

logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: DEBUG
    org.springframework.security: DEBUG
    
security:
  oauth2:
    sso:
      login-path: /login_success
    client:
      clientId: 142442864494-a61tnmr041dj375o5cks9fkjq43qdd4h.apps.googleusercontent.com
      clientSecret: CCBYpaLX-U5zLPFkxuoPmMxP
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      hd: zenika.com
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-unitaire
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-prod
  data:
    mongodb:
      host: localhost

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
