info:
  component: Liquid Democracy Api
  
logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: INFO
    org.springframework: ERROR

app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: /
    redirectUrlFailure: /
    
spring:
  social:
    google:
      appId: 
      appSecret: 

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost


---
spring:
  profiles: test-prod
  data:
    mongodb:
      host: localhost
logging:
  config: src/main/resources/log4j-test-prod.xml
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: http://localhost:8081/TestApi/success.html
    redirectUrlFailure: http://localhost:8081/TestApi/failure.html

---      
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
logging:
  config: src/main/resources/log4j-test-prod.xml
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: http://localhost:3000
    redirectUrlFailure: http://localhost:3000/#/loginfailed

---      
spring:
  profiles: docker-test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
