info:
  component: Liquid Democracy Api

logging:
  level:
    ROOT: INFO
    com.zenika.liquid.democracy: DEBUG

spring:
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
