info:
  component: Liquid Democracy Api
  
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl: /
    redirectUrlFailure: /
    applicationUrl: 


---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost

---      
spring:
  profiles: prod
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: mongoliquidDemocracy
      database: dbliqdem
  social:
    google:
      appId: 
      appSecret: 
app:
  config:
    rememberMeKey: thisisasimpleremembermekey
    redirectUrl:  
    redirectUrlFailure: /loginfailed
    applicationUrl: http://agora.zenika.com

